/** English source labels map into the plugin's existing Chinese-key translator. */
export const COMPOSER_ZH: Record<string, string> = {
    'Untitled': '无标题', 'Search': '搜索', 'View': '视图', 'More': '更多', 'Create Note': '创建笔记',
    'Search document and unsorted ideas': '搜索文档和灵感箱', 'Search Composer': '搜索 Composer', 'Search scope': '搜索范围',
    'Titles': '标题', 'Bodies': '正文', 'Everything': '全部', 'Previous': '上一项', 'Next': '下一项', 'Close search': '关闭搜索',
    'Unsorted Ideas': '灵感箱', 'Ideas Inbox': '灵感箱', 'Close Ideas': '关闭灵感箱', 'Ideas': '灵感箱',
    'Mind map. Enter adds a section, Tab adds a child.': '脑图。Enter 创建同级，Tab 创建子节点。',
    'Resize body panel': '调整正文面板宽度', 'Pin': '固定', 'Close Body': '关闭正文', 'Enter to add a section': '按 Enter 创建章节',
    'Node actions': '节点操作', 'Node menu': '节点菜单', 'Add body…': '添加正文…', 'Direct section body': '节点直属正文',
    'Write paragraphs, lists, quotes or code here. Create section headings in the mind map.': '在此编写段落、列表、引用或代码。在脑图中创建章节标题。',
    'Draft saved': '草稿已保存', 'Saved': '已保存', 'Saving draft…': '正在保存草稿…', 'Saving…': '正在保存…',
    'Draft not saved — retry or copy recovery data': '草稿未保存，请重试或复制恢复数据',
    'Expand branch': '展开分支', 'Collapse branch': '收起分支', 'Add child': '添加子节点', 'Complete ': '完成 ',
    'No results': '没有结果', 'Document introduction': '文档前言', 'Edit body': '编辑正文',
    'Move this idea into the document before focusing its branch.': '请先将此想法拖入文档，再聚焦其分支。',
    'New idea': '新想法', 'Expand / Collapse': '展开 / 折叠',
    'Capture ideas here before deciding where they belong.': '先记录想法，再拖入脑图组织成文。', 'Capture an idea…': '记录一个想法…',
    'As one idea': '作为一个想法', 'Split into lines': '按行拆分', 'Search ideas': '搜索灵感', 'Cancel': '取消', 'Confirm': '确认',
    'New unsorted idea': '记录灵感', 'Create parent from selection': '为选中节点创建父节点', 'New group': '新分组',
    'Document properties': '文档属性', 'YAML frontmatter, without --- delimiters. This is saved with the draft and placed before the introduction.': '填写 YAML 属性，不含 --- 分隔线。属性随草稿保存，导出后位于前言之前。',
    'Frontmatter YAML': 'YAML 文档属性', 'Save properties': '保存属性', 'Clipboard unavailable': '剪贴板不可用', 'Outline copied.': '已复制大纲。', 'Copy outline': '复制大纲',
    'New section title': '新节点标题', 'Rename node': '重命名节点', 'Delete this branch': '删除整个分支', 'Delete node but keep children': '删除节点并保留子节点',
    'Delete': '删除', 'Insert before': '插入到前面', 'Make child': '作为子节点', 'Insert after': '插入到后面',
    'Layout': '布局', 'Radial': '放射', 'Horizontal': '水平', 'Compact': '紧凑', 'Body': '正文', 'Fit to view': '适应窗口', 'Reset zoom': '重置缩放',
    'Auto': '自动', 'Show': '显示', 'Hide': '隐藏', 'Rename': '重命名', 'Duplicate': '复制', 'Branch': '分支',
    'Focus branch': '聚焦分支', 'Show overview': '查看全貌', 'Expand one level': '展开一级', 'Show to level…': '显示到指定层级…',
    'Show branch to level (1–6)': '分支显示层级（1–6）', 'Choose a level from 1 to 6.': '请选择 1 到 6 层。',
    'Node type': '节点类型', 'Heading': '标题', 'Idea': '想法', 'Todo': '待办', 'Rename document': '重命名文档', 'Edit introduction': '编辑前言',
    'Add top-level section': '添加顶级章节', 'Use root as H1': '根节点作为一级标题', 'Document Info': '文档信息',
    'New from template': '从模板新建', 'Duplicate draft': '复制草稿', 'Retry draft save': '重试保存草稿', 'Copy recovery data': '复制恢复数据',
    'Create Markdown Note': '创建 Markdown 笔记', 'Discard draft': '丢弃草稿', 'This draft has not been converted to a Markdown note.': '此草稿尚未转换为 Markdown 笔记。',
    'Discard': '丢弃', 'Draft recovery': '草稿恢复', 'Draft storage could not be confirmed. Copy this recovery data before closing Obsidian, or retry saving.': '无法确认草稿是否保存成功。请在关闭 Obsidian 前复制恢复数据，或重试保存。',
    'Select recovery data': '选中恢复数据', 'Retry save': '重试保存', 'Name': '名称', 'Location (existing vault folder)': '位置（仓库中已有文件夹）',
    'Root behavior': '根节点用途', 'Document name only': '仅作为文档名称', 'Idea export policy': '想法导出方式', 'Choose…': '请选择…',
    'Convert to headings': '转换为标题', 'Convert to bullet items': '转换为列表项', 'Exclude idea branches': '不导出想法分支', 'Review individually': '逐项检查',
    'Unsorted export policy': '灵感箱导出方式', 'Append to document': '追加到文档', 'Exclude and keep draft': '不导出并保留草稿',
    'Excluded branches remain in a saved draft after creation. Bullet and Todo branches become lists, including their descendants and bodies.': '未导出的分支会继续保存在草稿中。列表和待办分支及其后代、正文将转换为列表。',
    'Create an empty Markdown note if there are no sections': '没有章节时创建空白 Markdown 笔记', 'Markdown preview': 'Markdown 预览',
    'Preview Markdown': '预览 Markdown', 'Open existing note': '打开已有笔记', 'Create': '创建',
    'This mind map has no document sections. Confirm creation of an empty note.': '此脑图没有文档章节。请确认创建空白笔记。',
    'Choose an existing vault folder.': '请选择仓库中已有的文件夹。', 'A note with this name already exists. Choose another name or open the existing note.': '同名笔记已存在。请更换名称或打开已有笔记。',
    ' · Draft retained with excluded ideas.': ' · 含未导出想法的草稿已保留。', 'Review idea nodes': '检查想法节点',
    'Convert individual ideas to headings or todos, or open a node to edit it. Then create the note again.': '将想法逐项转为标题或待办，或打开节点编辑，然后再次创建笔记。',
    'Unsorted / ': '灵感箱 / ', 'Back to Create Note': '返回创建笔记', 'Enter YAML without --- delimiters.': '请填写不含 --- 分隔线的 YAML。',
    'Document properties must be a YAML mapping, such as tags: [research].': '文档属性必须是 YAML 映射，例如 tags: [research]。',
    'New Composer from template': '从模板新建 Composer', 'Blank': '空白', 'Restore Composer Draft': '恢复 Composer 草稿',
    'No unfinished drafts.': '没有未完成的草稿。', 'Rename draft': '重命名草稿', 'Draft name': '草稿名称', 'Save': '保存',
    'Close this draft tab first, or use Discard draft in its document menu.': '请先关闭此草稿标签页，或使用其文档菜单中的“丢弃草稿”。',
    'This removes the saved draft, including unsorted ideas.': '这将删除已保存的草稿，包括灵感箱中的内容。',
    'Restore from recovery data': '从恢复数据导入', 'Paste draft recovery JSON': '粘贴草稿恢复 JSON', 'Restore as a new draft': '恢复为新草稿',
    'This draft could not be found. Open a saved draft from Restore Composer Draft.': '找不到此草稿。请通过“恢复 Composer 草稿”打开已保存的草稿。',
    'Invalid draft.': '草稿无效。', 'Unsupported draft format.': '不支持此草稿格式。', 'Unsupported node type.': '不支持此节点类型。',
    'Duplicate or invalid node IDs.': '节点 ID 重复或无效。', 'Maximum Markdown heading depth reached.': '已达到 Markdown 标题的最大层级。',
    'Invalid draft node.': '草稿节点无效。', 'Every node needs a single-line title.': '每个节点都需要单行标题。',
    'Select a section or idea, not the document root.': '请选择章节或想法，而非文档根节点。', 'Choose another destination.': '请选择其他目标。',
    'A branch cannot be moved into itself.': '不能将分支移动到自身或其后代中。', 'Enter a parent title.': '请输入父节点标题。',
    'Select one or more sibling nodes.': '请选择一个或多个同级节点。', 'Create parent requires nodes with the same parent.': '创建父节点要求所选节点属于同一个父节点。',
    'Choose how to handle Unsorted Ideas before exporting.': '导出前请选择灵感箱内容的处理方式。', 'Choose how to export idea nodes, or review them individually.': '请选择想法节点的导出方式，或逐项检查。',
    'Enter frontmatter YAML without --- delimiters.': '请填写不含 --- 分隔线的 YAML 属性。', 'Every exported node needs a single-line title.': '每个导出节点都需要单行标题。',
    'Body Markdown changes the section structure. Move headings into mind map nodes and close any unfinished code fences.': '正文中的 Markdown 改变了章节结构。请将标题移入脑图节点，并闭合未完成的代码块。',
    'Enter a valid Markdown filename.': '请输入有效的 Markdown 文件名。', 'Enter a valid vault folder.': '请输入有效的仓库文件夹。',
    'The document root cannot be moved.': '不能移动文档根节点。', 'Unknown template.': '未知模板。',
    'Select sibling nodes for this operation.': '此操作需要选择同级节点。', 'Select consecutive siblings for this operation.': '此操作需要选择连续的同级节点。',
    'There is no destination in that direction.': '该方向没有可移动的目标。',
    'Essay': '议论文', 'Introduction': '引言', 'Main Argument': '主要论点', 'Evidence': '论据', 'Counterargument': '反方观点', 'Conclusion': '结论',
    'Project Plan': '项目计划', 'Background': '背景', 'Goals': '目标', 'Scope': '范围', 'Milestones': '里程碑', 'Risks': '风险', 'Next Steps': '下一步',
    'Meeting Notes': '会议纪要', 'Agenda': '议程', 'Discussion': '讨论', 'Decisions': '决策', 'Action Items': '行动项',
    'Research Notes': '研究笔记', 'Question': '问题', 'Method': '方法', 'Findings': '发现', 'References': '参考资料',
    'Course Notes': '课程笔记', 'Overview': '概览', 'Key Concepts': '核心概念', 'Examples': '示例', 'Questions': '问题', 'Summary': '总结', ' (copy)': '（副本）',
    'New Mind Map Document': '新建脑图文档', 'New Mind Map Document here': '在此新建脑图文档', 'Composer: Search': 'Composer：搜索',
    'Delete {count} selected nodes?': '删除选中的 {count} 个节点？', 'Delete “{title}”?': '删除“{title}”？', 'Discard “{title}”?': '丢弃“{title}”？',
    'This draft contains {count} idea nodes. Export ideas as': '此草稿包含 {count} 个想法节点。导出方式', '{count} nodes in Unsorted Ideas': '灵感箱中有 {count} 个节点',
    '{title}: direct body': '{title}：直属正文', 'Type for {title}': '{title}的类型', 'Created {path}': '已创建 {path}',
    'Created {path}, but Organic Edit could not be initialized. Your draft is retained in Restore Composer Draft.': '已创建 {path}，但无法初始化 Organic 编辑模式。草稿仍保留在“恢复 Composer 草稿”中。',
    'sections': '章节', 'ideas': '想法', 'todos': '待办', 'completed': '已完成', 'unsorted': '待整理', 'words': '字词',
};
